/* SPLODER.Biped - Full biped mesh builder with constants and defaults */
    (SPLODER.Biped = function () {
        var e, t, i, s, o, n, a, r, h, l, E, d, R, P, c, u, O, L, S, T, D, m, f, p, g, y, I, w, v, _, M, A, N, x, Y, C, b, V, U;
        (this.poses = null),
            (this.initWithRectAndMaterial = function (i, s, h, l) {
                return (e = i), (t = s), (o = h || 0), (n = l || 0), (a = new THREE.Group()), (a.userData.biped = this), (r = new THREE.Group()), (r.userData.biped = this), a.add(r), (V = []), (U = [s]), this;
            }),
            (this.setItemMaterials = function (e, t, o, n) {
                (s = e), (x = t), (i = o), (N = n), U.push(s, i);
            });
        var F = function (i, s, o, n, a, r, h, l) {
            var E = SPLODER.MeshUtils.getPlaneGeometry(i, s, o, n, a, r, h, l),
                d = new THREE.Mesh(E, t);
            return (d.userData.rect = e), d;
        },
            G = function (i, s, o, n, a, r, h, l, E, d, R) {
                var P = SPLODER.MeshUtils.getBoxGeometry(i, s, o, n, a, r, h, l, E, d, R),
                    c = new THREE.Mesh(P, t);
                return (c.userData.rect = e), c;
            };
        this.build = function () {
            var U,
                z,
                B = e.getAttrib(SPLODER.Biped.PROPERTY_HEIGHT) / 255 + 0.5,
                H = e.getAttrib(SPLODER.Biped.PROPERTY_WEIGHT) / 255 + 0.5,
                k = e.getAttrib(SPLODER.Biped.PROPERTY_STRENGTH) / 128,
                X = e.getAttrib(SPLODER.Biped.PROPERTY_GENDER) / 128,
                W = e.getAttrib(SPLODER.Biped.PROPERTY_HEADSIZE) / 128,
                j = e.getAttrib(SPLODER.Biped.PROPERTY_HEADTHICK) / 128,
                Q = e.getAttrib(SPLODER.Biped.PROPERTY_BEASTLY) / 128;
            (r.position.y = 96 * SPLODER.weightedValue(0, B, 0.5)),
                (b = F(80 * SPLODER.weightedValue(0, H, 0.5), 48 * SPLODER.weightedValue(0, H, 0.5, k, 0.25))),
                (b.material = new THREE.MeshBasicMaterial({ color: 0, transparent: !0, opacity: 0.2 })),
                (b.position.y = 4),
                (b.rotation.x = 0 - 0.5 * Math.PI),
                a.add(b),
                (b = b.clone()),
                (b.material = new THREE.MeshBasicMaterial({ color: 0, transparent: !0, opacity: 0.1 })),
                b.scale.multiplyScalar(1.5),
                (b.position.y = 3),
                a.add(b),
                (h = G(60 * SPLODER.weightedValue(0, H, 0.5), 32 * SPLODER.weightedValue(0, B, 0.5), 32 * SPLODER.weightedValue(0, H, 0.5, k, 0.25), 0, -16 * SPLODER.weightedValue(0, B, 0.5), 0, 2, 1, 1)),
                (z = h.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 3, 19, 10, 5, 19, 19, 10, 5, 3, 19, 1, 5, 3, 19, 1, 1),
                (U[0].x -= 4 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[1].x -= 4 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[4].x += 4 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[5].x += 4 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[1].y += 8 * SPLODER.weightedValue(0, B, 0.5)),
                (U[4].y += 8 * SPLODER.weightedValue(0, B, 0.5)),
                (U[8].y += 8 * SPLODER.weightedValue(0, B, 0.5)),
                (U[1].z += 4),
                (U[4].z += 4),
                (U[8].z += 4),
                (U[3].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[11].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[6].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[0].z += 64 * SPLODER.weightedValue(-0.9, H, 0.25) - 4 * Q),
                (U[5].z += 64 * SPLODER.weightedValue(-0.9, H, 0.25) - 4 * Q),
                (U[9].z += 64 * SPLODER.weightedValue(-0.9, H, 0.25) - 4 * Q),
                (U[2].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[7].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[10].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[2].x += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[7].x -= 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[3].x += 8 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[6].x -= 9 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (h.rotation.x -= 0.1 * SPLODER.weightedValue(-0.5, Q, 1)),
                (h.position.z -= 12 * SPLODER.weightedValue(-0.5, Q, 1)),
                r.add(h),
                (l = G(68 * SPLODER.weightedValue(0, H, 0.5), 48 * SPLODER.weightedValue(0, B, 0.5), 32 * SPLODER.weightedValue(0, H, 0.5, k, 0.25), 0, 24 * SPLODER.weightedValue(0, B, 0.5), 0, 2, 2, 1)),
                (z = l.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 3, 11, 10, 8, 19, 11, 10, 8, 3, 11, 1, 8, 3, 11, 10, 1),
                (U[2].z += 5 + 2 * SPLODER.weightedValue(0, X, 0.5)),
                (U[9].z += 5 + 2 * SPLODER.weightedValue(0, X, 0.5)),
                (U[16].z += 5 * SPLODER.weightedValue(0, X, 0.5)),
                (U[17].z -= 0),
                (U[2].z += 5 * SPLODER.weightedValue(0, H, 1)),
                (U[9].z += 5 * SPLODER.weightedValue(0, H, 1)),
                (U[16].z += 5 * SPLODER.weightedValue(0, H, 1)),
                (U[0].x -= 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[1].x -= 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[2].x -= 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[3].x -= 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[6].x += 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[7].x += 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[8].x += 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[9].x += 0 - 3 * SPLODER.weightedValue(-0.75, k, 1, H, 0.25)),
                (U[4].x -= 8 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[5].x -= 8 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[10].x += 8 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[11].x += 8 - 8 * SPLODER.weightedValue(-1, H, 1)),
                (U[4].z += 80 * SPLODER.weightedValue(-0.9, H, 0.25)),
                (U[14].z += 80 * SPLODER.weightedValue(-0.9, H, 0.25)),
                (U[11].z += 80 * SPLODER.weightedValue(-0.9, H, 0.25)),
                (U[4].y += Math.min(0, 80 * SPLODER.weightedValue(-0.9, Q, 0.25))),
                (U[14].y += Math.min(0, 80 * SPLODER.weightedValue(-0.9, Q, 0.25))),
                (U[11].y += Math.min(0, 80 * SPLODER.weightedValue(-0.9, Q, 0.25))),
                (l.rotation.x += 0.3 * SPLODER.weightedValue(-0.5, Q, 1)),
                (l.position.z -= 12 * SPLODER.weightedValue(-0.5, Q, 1)),
                r.add(l),
                (E = G(32 * SPLODER.weightedValue(0, H, 0.8), 24 * SPLODER.weightedValue(0, B, 0.5), 18 * SPLODER.weightedValue(0, H, 0.8), 0, 12 * SPLODER.weightedValue(0, B, 0.5), 0)),
                (E.position.y += 42 * SPLODER.weightedValue(0, B, 0.5)),
                SPLODER.MeshUtils.transformUVs(E.geometry, o, n, 6, 10, 4, 1, 22, 10, 4, 1, 6, 10, 4, 1, 6, 10, 1, 1),
                (E.rotation.x += 0.3 * SPLODER.weightedValue(-0.5, Q, 1)),
                l.add(E),
                (d = G(42 * SPLODER.weightedValue(0, H, 0.25), 48 * SPLODER.weightedValue(0, j, 0.25), 42 * SPLODER.weightedValue(0, H, 0.25), 0, 24 * SPLODER.weightedValue(0, j, 0.25), 4, 1, 1, 1, !1, 0 - SPLODER.weightedValue(0, k, 16))),
                (d.position.y += 12 * SPLODER.weightedValue(0, B, 0.5, j, 0.5)),
                (d.position.z += 12 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (d.rotation.x -= 0.6 * SPLODER.weightedValue(-0.5, Q, 1)),
                0.25 > Q && (d.rotation.x -= 0.25 - SPLODER.weightedValue(0, Q, 1)),
                SPLODER.MeshUtils.transformUVs(d.geometry, o, n, 4, 1, 8, 9, 20, 1, 8, 9, 36, 1, 8, 9, 36, 11, 8, 8),
                d.scale.multiplyScalar(0.25 + SPLODER.weightedValue(0, W, 0.25)),
                E.add(d),
                (R = G(42 * SPLODER.weightedValue(0, H, 0.25), 8 * SPLODER.weightedValue(0, j, 0.25), 1, 0, 4 * SPLODER.weightedValue(0, j, 0.25), 0, 1, 1, 1, !1)),
                SPLODER.MeshUtils.transformUVs(R.geometry, o, n, 4, 0, 8, 1, 20, 0, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0),
                (R.position.y += 48 * SPLODER.weightedValue(0, j, 0.25)),
                (R.position.z += 18 * SPLODER.weightedValue(0, H, 0.25)),
                d.add(R),
                (P = G(24, 48 * SPLODER.weightedValue(0, j, 0.25), 2, 33 * SPLODER.weightedValue(0, H, 0.25) - 1, 24 * SPLODER.weightedValue(0, j, 0.25), 0, 1, 1, 1, !0)),
                SPLODER.MeshUtils.transformUVs(P.geometry, o, n, 12, 1, 4, 9, 16, 1, -4, 9, 0, 0, 0, 0, 0, 0, 0, 0),
                d.add(P),
                (c = G(24, 48 * SPLODER.weightedValue(0, j, 0.25), 2, -33 * SPLODER.weightedValue(0, H, 0.25) + 1, 24 * SPLODER.weightedValue(0, j, 0.25), 0)),
                SPLODER.MeshUtils.transformUVs(c.geometry, o, n, 0, 1, 4, 9, 4, 1, -4, 9, 0, 0, 0, 0, 0, 0, 0, 0),
                d.add(c),
                (u = G(1, 48 * SPLODER.weightedValue(0, j, 0.25), 24, 0, 24 * SPLODER.weightedValue(0, j, 0.25), -29 * SPLODER.weightedValue(0, H, 0.25))),
                SPLODER.MeshUtils.transformUVs(u.geometry, o, n, 0, 0, 0, 0, 0, 0, 0, 0, 32, 1, 4, 9, 0, 0, 0, 0),
                d.add(u),
                (O = new SPLODER.BipedFace().initWithRectAndMaterial(e, t, o, n)),
                O.build(),
                (O.mesh.position.z = 26.2 * Math.max(0.75, SPLODER.weightedValue(0, H, 0.25, j, 0.0125))),
                (O.mesh.position.y = 24 * SPLODER.weightedValue(0, j, 0.25, k, 0.125)),
                (O.mesh.rotation.x = 0 - SPLODER.weightedValue(-1, k, 0.08)),
                (O.mesh.scale.y = 1 * SPLODER.weightedValue(0, j, 0.25)),
                d.add(O.mesh),
                (f = G(50 * SPLODER.weightedValue(0, H, 0.25), 64 * SPLODER.weightedValue(0, j, 0.25), 44 * SPLODER.weightedValue(0, H, 0.25), 0, 20 * SPLODER.weightedValue(0, j, 0.25), 0, 1, 2, 1, !1, 0 - SPLODER.weightedValue(0, k, 24))),
                (z = f.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(f.geometry, o, n, 36, 19, 8, 8, 36, 19, 1, 8, 36, 19, 0.9, 8, 36, 19, 8, 1),
                (U[2].y -= 20),
                (U[3].y -= 20),
                (U[8].y -= 20),
                (U[9].y -= 20),
                (U[2].z -= 8),
                (U[9].z -= 8),
                (U[4].z -= 20),
                (U[5].z += 20),
                (U[10].z += 20),
                (U[11].z -= 20),
                d.add(f),
                (p = F(96 * SPLODER.weightedValue(0, H, 0.5), 84 * SPLODER.weightedValue(0, B, 0.5), 0, 42 * SPLODER.weightedValue(0, B, 0.5), 0)),
                SPLODER.MeshUtils.transformUVs(p.geometry, o, n, 64, 5, -16, 14),
                (p.position.z -= 20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25)),
                (p.rotation.x = 0 - (15 * Math.PI) / 180),
                l.add(p),
                (p = F(96 * SPLODER.weightedValue(0, H, 0.5), 84 * SPLODER.weightedValue(0, B, 0.5), 0, 42 * SPLODER.weightedValue(0, B, 0.5), 0)),
                (p.rotation.x = 0 - (15 * Math.PI) / 180),
                (p.position.z -= 20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25)),
                (p.rotation.y = Math.PI),
                SPLODER.MeshUtils.transformUVs(p.geometry, o, n, 48, 5, 16, 14),
                l.add(p),
                (g = F(96 * SPLODER.weightedValue(0, H, 0.5), 72 * SPLODER.weightedValue(0, B, 0.5), 0, -36 * SPLODER.weightedValue(0, B, 0.5), 0, 2, 1)),
                (z = g.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(g.geometry, o, n, 64, 19, -16, 12),
                (U[5].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[4].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[3].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[5].x += 16 * SPLODER.weightedValue(0, H, 0.5)),
                (U[3].x -= 16 * SPLODER.weightedValue(0, H, 0.5)),
                (g.position.z -= 20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25)),
                (g.rotation.x = (18 * Math.PI) / 180 - SPLODER.weightedValue(-0.9, Q, 0.5)),
                l.add(g),
                (y = g),
                (g = F(96 * SPLODER.weightedValue(0, H, 0.5), 72 * SPLODER.weightedValue(0, B, 0.5), 0, -36 * SPLODER.weightedValue(0, B, 0.5), 0, 2, 1)),
                (z = g.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(g.geometry, o, n, 48, 19, 16, 12),
                (U[5].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[4].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[3].y -= 16 * SPLODER.weightedValue(0, B, 1)),
                (U[5].x += 16 * SPLODER.weightedValue(0, H, 0.5)),
                (U[3].x -= 16 * SPLODER.weightedValue(0, H, 0.5)),
                (g.rotation.x = (18 * Math.PI) / 180 - SPLODER.weightedValue(-0.9, Q, 0.5)),
                (g.position.z -= 20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25)),
                (g.position.y += 0.5),
                (g.rotation.y = Math.PI),
                l.add(g),
                (L = G(
                    20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25),
                    40 * SPLODER.weightedValue(0, B, 0.5),
                    20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25),
                    0,
                    -16 * SPLODER.weightedValue(0, B, 0.5),
                    0,
                    1,
                    1,
                    1,
                    !0,
                    SPLODER.weightedValue(0, H, 64)
                )),
                (z = L.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 9, 24, 4, 4, 19, 24, 4, 4, 9, 24, 1, 4, 9, 24, 1, 1),
                (U[2].z -= 2),
                (U[7].z -= 2),
                (L.position.x += 14 * SPLODER.weightedValue(0, H, 0.25)),
                (L.position.y -= 28 * SPLODER.weightedValue(0, B, 0.5)),
                (L.rotation.x -= 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                (L.rotation.z += 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                (L.rotation.y += 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                h.add(L),
                (T = G(22 * SPLODER.weightedValue(0, H, 0.25, k, 0.25), 32 * SPLODER.weightedValue(0, B, 0.5), 20 * SPLODER.weightedValue(0, H, 0.25, k, 0.25), 0, -16 * SPLODER.weightedValue(0, B, 0.5), 0, 1, 3, 1, !0)),
                (z = T.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 9, 28, 4, 4, 19, 28, 4, 4, 9, 28, 1, 4, 9, 28, 1, 1),
                (U[0].y += 10),
                (U[9].y += 10),
                (U[4].y += 5),
                (U[6].y += 5),
                (U[13].y += 5),
                (U[15].y += 5),
                (U[4].z += 10),
                (U[6].z += 10),
                (U[13].z += 10),
                (U[15].z += 10),
                (T.position.y = -36 * SPLODER.weightedValue(0, B, 0.5)),
                (T.rotation.x += 0.4 * SPLODER.weightedValue(0, Q, 1)),
                L.add(T),
                (S = G(
                    20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25),
                    40 * SPLODER.weightedValue(0, B, 0.5),
                    20 * SPLODER.weightedValue(0, H, 0.5, k, 0.25),
                    0,
                    -16 * SPLODER.weightedValue(0, B, 0.5),
                    0,
                    1,
                    1,
                    1,
                    !1,
                    SPLODER.weightedValue(0, H, 64)
                )),
                (z = S.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 3, 24, 4, 4, 25, 24, 4, 4, 3, 24, 1, 4, 3, 24, 1, 1),
                (U[2].z -= 2),
                (U[7].z -= 2),
                (S.position.x -= 14 * SPLODER.weightedValue(0, H, 0.25)),
                (S.position.y -= 28 * SPLODER.weightedValue(0, B, 0.5)),
                (S.rotation.y -= 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                (S.rotation.z -= 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                (S.rotation.x -= 0.2 * SPLODER.weightedValue(0, Q, 1) * Math.min(1, H)),
                h.add(S),
                (D = G(22 * SPLODER.weightedValue(0, H, 0.25, k, 0.25), 32 * SPLODER.weightedValue(0, B, 0.5), 20 * SPLODER.weightedValue(0, H, 0.25, k, 0.25), 0, -16 * SPLODER.weightedValue(0, B, 0.5), 0, 1, 3, 1)),
                (z = D.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 3, 28, 4, 4, 25, 28, 4, 4, 3, 28, 1, 4, 3, 28, 1, 1),
                (U[0].y += 10),
                (U[9].y += 10),
                (U[4].y += 5),
                (U[6].y += 5),
                (U[13].y += 5),
                (U[15].y += 5),
                (U[4].z += 10),
                (U[6].z += 10),
                (U[13].z += 10),
                (U[15].z += 10),
                (D.position.y = -36 * SPLODER.weightedValue(0, B, 0.5)),
                (D.rotation.x += 0.4 * SPLODER.weightedValue(0, Q, 1)),
                S.add(D),
                (m = G(60 * SPLODER.weightedValue(0, H, 0.5), 48 * SPLODER.weightedValue(0, B, 0.5), 32 * SPLODER.weightedValue(0, H, 0.5, k, 0.25), 0, -24 * SPLODER.weightedValue(0, B, 0.5), 0, 3)),
                (z = m.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 7, 24, 2, 6, 23, 24, 2, 6, 7, 24, 1, 6, 7, 24, 1, 1),
                (U[2].x += 6 * SPLODER.weightedValue(0, X, 0.25)),
                (U[3].x += 6 * SPLODER.weightedValue(0, X, 0.25)),
                (U[6].x -= 6 * SPLODER.weightedValue(0, X, 0.25)),
                (U[7].x -= 6 * SPLODER.weightedValue(0, X, 0.25)),
                (U[1].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[4].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[8].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[9].z -= 12 * SPLODER.weightedValue(-0.5, H, 0.5)),
                (U[3].z -= 24 * SPLODER.weightedValue(0, X, 0.25)),
                (U[6].z -= 24 * SPLODER.weightedValue(0, X, 0.25)),
                (U[14].z -= 24 * SPLODER.weightedValue(0, X, 0.25)),
                (U[15].z -= 24 * SPLODER.weightedValue(0, X, 0.25)),
                (U[12].z += 16 * SPLODER.weightedValue(0, X, 0.25)),
                (U[13].z += 16 * SPLODER.weightedValue(0, X, 0.25)),
                (U[2].z += 8 * SPLODER.weightedValue(0, X, 0.25)),
                (U[7].z += 8 * SPLODER.weightedValue(0, X, 0.25)),
                (U[0].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[5].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[10].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[11].z += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[0].x += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[5].x -= 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[2].x += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[7].x -= 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[1].x += 8 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[4].x -= 8 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[3].x += 8 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[6].x -= 8 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[3].y += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[6].y += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[14].y += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (U[15].y += 16 * SPLODER.weightedValue(-0.5, Q, 0.5)),
                (m.position.y = -32 * SPLODER.weightedValue(0, B, 0.5)),
                h.add(m),
                (I = G(
                    16 * SPLODER.weightedValue(0, k, 0.35),
                    42 * SPLODER.weightedValue(0, B, 0.5),
                    20 * SPLODER.weightedValue(0, k, 0.35, X, -0.25),
                    0,
                    -20 * SPLODER.weightedValue(0, B, 0.5),
                    0,
                    1,
                    1,
                    1,
                    !0,
                    Math.max(0, SPLODER.weightedValue(0, k, 24))
                )),
                (z = I.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 13, 11, 3, 7, 16, 11, 3, 7, 15, 11, 1, 7, 15, 11, 1, 1),
                (U[4].y += 5),
                (U[5].y += 5),
                (U[3].z += 5 * SPLODER.weightedValue(0, k, 0.35, X, -0.25)),
                (U[6].z += 5 * SPLODER.weightedValue(0, k, 0.35, X, -0.25)),
                (I.position.x = 40 * SPLODER.weightedValue(0, H, 0.5) + SPLODER.weightedValue(0, k, 4)),
                (I.position.y += 42 * SPLODER.weightedValue(0, B, 0.5)),
                (I.rotation.z += 0.2 * SPLODER.weightedValue(0, Q, 1)),
                (I.rotation.x -= 0.4 * SPLODER.weightedValue(0, Q, 1)),
                l.add(I),
                (w = G(
                    16 * SPLODER.weightedValue(0, k, 0.35),
                    42 * SPLODER.weightedValue(0, B, 0.5),
                    20 * SPLODER.weightedValue(0, k, 0.35, X, -0.25),
                    0,
                    -20 * SPLODER.weightedValue(0, B, 0.5),
                    0,
                    1,
                    1,
                    1,
                    !1,
                    Math.max(0, SPLODER.weightedValue(0, k, 24))
                )),
                (z = w.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 0, 11, 3, 7, 29, 11, 3, 7, 0, 11, 1, 7, 0, 11, 1, 1),
                (U[0].y += 5),
                (U[1].y += 5),
                (U[3].z += 5 * SPLODER.weightedValue(0, k, 0.35, X, -0.25)),
                (U[6].z += 5 * SPLODER.weightedValue(0, k, 0.35, X, -0.25)),
                (w.position.x = -40 * SPLODER.weightedValue(0, H, 0.5) - SPLODER.weightedValue(0, k, 4)),
                (w.position.y += 42 * SPLODER.weightedValue(0, B, 0.5)),
                (w.rotation.z -= 0.2 * SPLODER.weightedValue(0, Q, 1)),
                (w.rotation.x -= 0.4 * SPLODER.weightedValue(0, Q, 1)),
                l.add(w),
                (v = G(18 * SPLODER.weightedValue(0, k, 0.35), 42 * SPLODER.weightedValue(0, B, 0.5), 22 * SPLODER.weightedValue(0, k, 0.35, X, -0.25), 0, -21 * SPLODER.weightedValue(0, B, 0.5), 0, 1, 4, 1, !0)),
                (z = v.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 13, 18, 3, 6, 16, 18, 3, 6, 15, 18, 1, 6, 15, 18, 1, 1),
                (U[1].y += 10),
                (U[10].y += 10),
                (U[4].x -= 3),
                (U[4].z -= 3),
                (U[5].x -= 3),
                (U[5].z += 3),
                (U[14].x += 3),
                (U[14].z += 3),
                (U[15].x += 3),
                (U[15].z -= 3),
                (U[8].x -= 3),
                (U[8].z -= 3),
                (U[9].x -= 3),
                (U[9].z += 3),
                (U[18].x += 3),
                (U[18].z += 3),
                (U[19].x += 3),
                (U[19].z -= 3),
                (v.position.y = -40 * SPLODER.weightedValue(0, B, 0.5)),
                (v.rotation.z -= 0.2 * SPLODER.weightedValue(0, Q, 1)),
                (v.rotation.x -= 0.2 * SPLODER.weightedValue(0, Q, 1)),
                I.add(v),
                i && N && ((M = new SPLODER.BipedItem().initWithRectAndMaterial(e, i, N)), M.build(), (M.mesh.rotation.y = 1.57), (M.mesh.position.x += 8), v.add(M.mesh)),
                (_ = G(18 * SPLODER.weightedValue(0, k, 0.35), 42 * SPLODER.weightedValue(0, B, 0.5), 22 * SPLODER.weightedValue(0, k, 0.35, X, -0.25), 0, -21 * SPLODER.weightedValue(0, B, 0.5), 0, 1, 4, 1)),
                (z = _.geometry),
                (U = z.vertices),
                SPLODER.MeshUtils.transformUVs(z, o, n, 0, 18, 3, 6, 29, 18, 3, 6, 0, 18, 1, 6, 0, 18, 1, 1),
                (U[1].y += 10),
                (U[10].y += 10),
                (U[4].x -= 3),
                (U[4].z -= 3),
                (U[5].x -= 3),
                (U[5].z += 3),
                (U[14].x += 3),
                (U[14].z += 3),
                (U[15].x += 3),
                (U[15].z -= 3),
                (U[8].x -= 3),
                (U[8].z -= 3),
                (U[9].x -= 3),
                (U[9].z += 3),
                (U[18].x += 3),
                (U[18].z += 3),
                (U[19].x += 3),
                (U[19].z -= 3),
                (_.position.y = -40 * SPLODER.weightedValue(0, B, 0.5)),
                (_.rotation.z += 0.2 * SPLODER.weightedValue(0, Q, 1)),
                (_.rotation.x -= 0.2 * SPLODER.weightedValue(0, Q, 1)),
                w.add(_),
                (Y = F(21 * SPLODER.weightedValue(0, k, 0.35, X, -0.25), 22 * SPLODER.weightedValue(0, B, 0.5), 0, 11 * SPLODER.weightedValue(0, B, 0.5), 0)),
                (Y.position.y -= 53.25 * SPLODER.weightedValue(0, B, 0.5)),
                (Y.position.x += 8.75 * SPLODER.weightedValue(0, k, 0.35)),
                (Y.rotation.y = 0.5 * Math.PI),
                SPLODER.MeshUtils.transformUVs(Y.geometry, o, n, 13, 24, 5, 5),
                v.add(Y),
                (Y = Y.clone()),
                (Y.rotation.y = 0.5 * -Math.PI),
                v.add(Y),
                (C = F(21 * SPLODER.weightedValue(0, k, 0.35, X, -0.25), 22 * SPLODER.weightedValue(0, B, 0.5), 0, 11 * SPLODER.weightedValue(0, B, 0.5), 0)),
                (C.position.y -= 53.25 * SPLODER.weightedValue(0, B, 0.5)),
                (C.position.x -= 8.75 * SPLODER.weightedValue(0, k, 0.35)),
                (C.rotation.y = 0.5 * -Math.PI),
                SPLODER.MeshUtils.transformUVs(C.geometry, o, n, 13, 24, 5, 5),
                _.add(C),
                (C = C.clone()),
                (C.rotation.y = 0.5 * Math.PI),
                _.add(C),
                s && x && ((A = new SPLODER.BipedItem().initWithRectAndMaterial(e, s, x)), A.build(), _.add(A.mesh)),
                (z = h.geometry),
                (U = z.vertices),
                (U[0].x -= 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[1].x -= 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[4].x += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[5].x += 4 * SPLODER.weightedValue(-1, X, 1)),
                (z = l.geometry),
                (U = z.vertices),
                (U[4].x -= 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[5].x -= 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[10].x += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[11].x += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[2].y += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[9].y += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[2].z += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[9].z += 4 * SPLODER.weightedValue(-1, X, 1)),
                (U[0].y -= 4 * SPLODER.weightedValue(-0.5, X, 1)),
                (U[1].y -= 4 * SPLODER.weightedValue(-0.5, X, 1)),
                (U[6].y -= 4 * SPLODER.weightedValue(-0.5, X, 1)),
                (U[7].y -= 4 * SPLODER.weightedValue(-0.5, X, 1)),
                (U[0].z -= 4 * SPLODER.weightedValue(-1, X, 1, H, 0.5)),
                (U[1].z += 4 * SPLODER.weightedValue(-1, X, 1, H, 0.5)),
                (U[6].z += 4 * SPLODER.weightedValue(-1, X, 1, H, 0.5)),
                (U[7].z -= 4 * SPLODER.weightedValue(-1, X, 1, H, 0.5)),
                (I.position.y -= 4 * SPLODER.weightedValue(-0.5, X, 1)),
                (w.position.y -= 4 * SPLODER.weightedValue(-0.5, X, 1));
            var q = function (e) {
                V.push(e.geometry);
                for (var t = e.children.length; t--;) q(e.children[t]);
            };
            q(r), (this.poses = new SPLODER.BipedPoses().initWithElements(e, r, h, l, E, O, L, S, I, w, g, y, A, M));
        };
        var z = function (e, t, i) {
            (i = i || r), SPLODER.MeshUtils.offsetUVsRecursive(e, t, i);
        };
        (this.destroy = function () {
            O && (O.destroy(), (O = null)), this.poses && (this.poses.destroy(), (this.poses = null));
        }),
            Object.defineProperty(this, "skinX", {
                get: function () {
                    return o;
                },
                set: function (e) {
                    if (!isNaN(e)) {
                        var t = e - o;
                        z(t, 0), (o = e);
                    }
                },
            }),
            Object.defineProperty(this, "skinY", {
                get: function () {
                    return n;
                },
                set: function (e) {
                    if (!isNaN(e)) {
                        var t = e - n;
                        z(0, t), (n = e);
                    }
                },
            }),
            Object.defineProperty(this, "mesh", {
                get: function () {
                    return a;
                },
            }),
            Object.defineProperty(this, "itemLeft", {
                get: function () {
                    return M;
                },
            }),
            Object.defineProperty(this, "itemRight", {
                get: function () {
                    return A;
                },
            }),
            Object.defineProperty(this, "geometries", {
                get: function () {
                    return V;
                },
            }),
            Object.defineProperty(this, "materials", {
                get: function () {
                    return U;
                },
            });
    }),
    (SPLODER.Biped.PROPERTY_SKIN = 5),
    (SPLODER.Biped.PROPERTY_HEIGHT = 6),
    (SPLODER.Biped.PROPERTY_WEIGHT = 7),
    (SPLODER.Biped.PROPERTY_STRENGTH = 8),
    (SPLODER.Biped.PROPERTY_GENDER = 9),
    (SPLODER.Biped.PROPERTY_HEADSIZE = 10),
    (SPLODER.Biped.PROPERTY_HEADTHICK = 11),
    (SPLODER.Biped.PROPERTY_BEASTLY = 12),
    (SPLODER.Biped.PROPERTY_ITEMFRAME_RIGHT = 13),
    (SPLODER.Biped.PROPERTY_ITEMFRAME_LEFT = 14),
    (function (e, t) {
        (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_SKIN] = 0),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_HEIGHT] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_WEIGHT] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_STRENGTH] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_GENDER] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_HEADSIZE] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_HEADTHICK] = 128),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_BEASTLY] = 64),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_ITEMFRAME_RIGHT] = -1),
            (e.defaultsByType[e.TYPE_BIPED][t.PROPERTY_ITEMFRAME_LEFT] = -1);
    })(SPLODER.Item, SPLODER.Biped),
